# Generated by Django 2.2.4 on 2020-04-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientnam', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=15)),
                ('proj_date', models.DateField()),
                ('cimg', models.ImageField(upload_to='gallery')),
                ('des1', models.CharField(max_length=150)),
                ('des2', models.CharField(max_length=150)),
                ('thumb_img1', models.ImageField(upload_to='gallery')),
                ('thumb_img2', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='img',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
