# Generated by Django 2.2.4 on 2020-04-24 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200423_2116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceB',
            new_name='AboutService',
        ),
    ]
